spring.application.name=barberia_backend
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres
# ------------------------------------------------------------------------
# 2. CREDENCIALES
# ------------------------------------------------------------------------
spring.datasource.username=postgres.hjajsuktbhtvkcapxaeg
#la contraseña
spring.datasource.password=2By9OvhMZSJubGud
# ------------------------------------------------------------------------
# 3. CONFIGURACIÓN DE HIBERNATE / JPA
# ------------------------------------------------------------------------
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Para ver las consultas SQL en la consola (útil en desarrollo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Esto crea/actualiza las tablas en Supabase basándose en tus @Entity
spring.jpa.hibernate.ddl-auto=update
app.jwt.secret=CAMBIA_ESTO_POR_UN_SECRET_DE_AL_MENOS_32_CARACTERES_ALEATORIOS
app.jwt.expiration-ms=3600000
app.cors.allowed-origins=http://localhost:4200